# Podemos utilizar este para hacer la limpieza completa del DF, y luego lo guardamos, y es el que vamos a cargar para el análisis.

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("./data/listings.csv")

In [4]:
df.head(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,96033,"Bonito piso a 200m de la playa, El Palo (Málaga)",510467,Rafael,NaN,Este,36.720310,-4.356270,Entire home/apt,58.0,3,274,2025-09-29,1.88,1,324,40,ESFCTU0000290200003588210000000000000000VUT/MA...
1,166473,Perfect Location In Malaga,793360,Fred,NaN,Este,36.720310,-4.361080,Private room,28.0,5,102,2025-03-27,0.59,5,288,3,NaN
2,330760,Malaga Lodge Guesthouse Double room-shared bath.,1687526,Mayte,NaN,Centro,36.729786,-4.413462,Private room,60.0,1,68,2025-09-04,0.41,6,64,12,ESHFTU0000290200004234200060000000000000VFT/MA...
3,340024,NEW APARTMENT IN MALAGA CENTER,1725690,Carlos,NaN,Centro,36.728130,-4.414220,Entire home/apt,61.0,3,322,2025-09-09,2.11,1,297,38,VFT/MA/02334
4,358541,Casa La Maga - Apartment for happy people,1526932,Cristina,NaN,Centro,36.723740,-4.421300,Entire home/apt,87.0,2,405,2025-07-27,2.48,1,195,23,VFT/MA/02288

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9714 entries, 0 to 9713
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              9714 non-null   int64
 1   name                            9714 non-null   str
 2   host_id                         9714 non-null   int64
 3   host_name                       9714 non-null   str
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   9714 non-null   str
 6   latitude                        9714 non-null   float64
 7   longitude                       9714 non-null   float64
 8   room_type                       9714 non-null   str
 9   price                           8815 non-null   float64
 10  minimum_nights                  9714 non-null   int64
 11  number_of_reviews               9714 non-null   int64
 12  last_review                     8709 non-null   str
 13  reviews_per_month               8709 non-null   float64
 14  calculated_host_listings_count  9714 non-null   int64
 15  availability_365                9714 non-null   int64
 16  number_of_reviews_ltm           9714 non-null   int64
 17  license                         9587 non-null   str
dtypes: float64(5), int64(7), str(6)
memory usage: 1.3 MB

In [6]:
df.isnull().sum()

id                                   0
name                                 0
host_id                              0
host_name                            0
neighbourhood_group               9714
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price                              899
minimum_nights                       0
number_of_reviews                    0
last_review                       1005
reviews_per_month                 1005
calculated_host_listings_count       0
availability_365                     0
number_of_reviews_ltm                0
license                            127
dtype: int64

In [7]:
# la columna de neighbourhood_group nos la podemos cargar directamente
df = df.drop(columns=["neighbourhood_group"])

In [ ]:
# considero que los precios nulos y las reseñas tmb son importantes y son demasiados datos nulos en un DF,
# podemos analizar si eliminarlas directamente o ver que hacer con ellas
# reviews_per_month
# last_review
# reviews_per_month
# license nulos, hay que ver que tipo de apartamentos/habitaciones son

In [ ]:
# no hay duplicados
df.duplicated().sum()

np.int64(0)

In [ ]:
# hay 9 filas con mas de 2 nulos
# yo tmb las eliminaria
df[df.isnull().sum(axis=1) > 3]

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
1536,30220252,"4 dormitorios, Piscina y jardin comunitarios.",226962261,Houria,Palma-Palmilla,36.733140,-4.434900,Entire home/apt,NaN,63,0,NaN,NaN,1,365,0,NaN
5892,1030406840249566662,Ático moderno Málaga,55095306,Cristobal,Cruz De Humilladero,36.716165,-4.454274,Entire home/apt,NaN,60,0,NaN,NaN,1,0,0,NaN
5900,1031858964149323517,Ático Litoral Beach Málaga,423394067,Patricio,Carretera de Cadiz,36.686511,-4.448111,Entire home/apt,NaN,60,0,NaN,NaN,1,0,0,NaN
7019,1184460960909551312,Habitación en Málaga Centro,554899916,Jose Antonio,Centro,36.721480,-4.429980,Private room,NaN,60,0,NaN,NaN,1,19,0,NaN
7950,1280502680524978930,Moderno apto. vistas panoramicas,240233474,María Jose,Palma-Palmilla,36.729730,-4.427360,Entire home/apt,NaN,60,0,NaN,NaN,1,358,0,NaN
8297,1330552227086469359,Residencial Capuchinos habitaciones con aire a...,547690910,Paula,Centro,36.732371,-4.417316,Entire home/apt,NaN,3,0,NaN,NaN,3,364,0,NaN
8306,1332070763361153256,Bright room close to stadium.,21018683,Kim Søren Wammen,Ciudad Jardin,36.735995,-4.421095,Private room,NaN,60,0,NaN,NaN,1,28,0,NaN
8570,1370643078501669599,Charmante Wohnung im Malaga Centro,105731399,Fereshteh,Centro,36.729691,-4.424361,Entire home/apt,NaN,60,0,NaN,NaN,4,365,0,NaN
8845,1402918315385930065,SkyLodge 26,372877619,Daniel,Palma-Palmilla,36.730355,-4.426825,Entire home/apt,NaN,60,0,NaN,NaN,1,365,0,NaN

In [10]:
df[df["license"].isnull()].head()

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
1,166473,Perfect Location In Malaga,793360,Fred,Este,36.72031,-4.36108,Private room,28.0,5,102,2025-03-27,0.59,5,288,3,NaN
38,1071665,HEART HISTORICAL CITY. Santos street,5895070,Miren Arantza,Centro,36.72038,-4.42298,Entire home/apt,63.0,5,295,2025-09-28,1.99,3,350,28,NaN
51,1378908,BEST LOCATION+WIFI- CITY CENTRE,5895070,Miren Arantza,Centro,36.71984,-4.42222,Entire home/apt,76.0,5,271,2025-09-10,1.84,3,325,22,NaN
69,1966333,Perfect Location in Malaga Part 2,793360,Fred,Este,36.72029,-4.36088,Private room,28.0,5,50,2025-02-25,0.35,5,288,1,NaN
71,2138517,Casa Rural Carpe Diem de Málaga,9725526,Isabel,Churriana,36.65388,-4.51556,Entire home/apt,NaN,4,4,2023-05-16,0.10,1,0,0,NaN

In [11]:
df[df["license"].isnull()]["room_type"].value_counts()

room_type
Entire home/apt    90
Private room       37
Name: count, dtype: int64

In [ ]:
# comprobar que las ultimas reseñas estén en el año 2025 y 2024.
# para ello debemos comprobar que la columna last_review es una fecha
df["last_review"] = pd.to_datetime(df["last_review"], errors="coerce")

In [ ]:
# ya que hay bastantos datos en el año 2025, podríamos estudiar solo los del año 2025... 
# # de esta forma, nos aseguramos que las columnas de last_reviews y reviews_per_month no tengan nulos
df_2025 = df[df["last_review"].dt.year == 2025]

In [20]:
df_2025.info()

<class 'pandas.DataFrame'>
Index: 7338 entries, 0 to 9688
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              7338 non-null   int64
 1   name                            7338 non-null   str
 2   host_id                         7338 non-null   int64
 3   host_name                       7338 non-null   str
 4   neighbourhood                   7338 non-null   str
 5   latitude                        7338 non-null   float64
 6   longitude                       7338 non-null   float64
 7   room_type                       7338 non-null   str
 8   price                           6861 non-null   float64
 9   minimum_nights                  7338 non-null   int64
 10  number_of_reviews               7338 non-null   int64
 11  last_review                     7338 non-null   datetime64[us]
 12  reviews_per_month               7338 non-null   float64
 13  calculated_host_listings_count  7338 non-null   int64
 14  availability_365                7338 non-null   int64
 15  number_of_reviews_ltm           7338 non-null   int64
 16  license                         7282 non-null   str
dtypes: datetime64[us](1), float64(4), int64(7), str(5)
memory usage: 1.0 MB

In [ ]:
# Tenemos 56 nulos en licence (de esta podriamos analizar si los alojamientos sin licencia son mas baratos, 
    # o tienen mayor disponibilidad)

# 477 nulos en price(que yo estas filas tmb las eliminaria)
df_2025.isnull().sum()

id                                  0
name                                0
host_id                             0
host_name                           0
neighbourhood                       0
latitude                            0
longitude                           0
room_type                           0
price                             477
minimum_nights                      0
number_of_reviews                   0
last_review                         0
reviews_per_month                   0
calculated_host_listings_count      0
availability_365                    0
number_of_reviews_ltm               0
license                            56
dtype: int64

In [ ]:
# las columnas latitude y longitude, realmente no aportan nada, ya que en neighbourhood, las tenemos clasificadas

In [ ]:
# podemos comprobar ahora si existiran mas de dos nulos (price y license)
df_2025[df_2025.isnull().sum(axis=1) > 3]
# no hay

Empty DataFrame
Columns: [id, name, host_id, host_name, neighbourhood, latitude, longitude, room_type, price, minimum_nights, number_of_reviews, last_review, reviews_per_month, calculated_host_listings_count, availability_365, number_of_reviews_ltm, license]
Index: []

In [28]:
df_2025["neighbourhood"].value_counts()

neighbourhood
Centro                  4912
Este                     728
Carretera de Cadiz       699
Cruz De Humilladero      326
Bailen-Miraflores        229
Palma-Palmilla           162
Churriana                114
Ciudad Jardin             62
Teatinos-Universidad      56
Puerto de la Torre        30
Campanillas               20
Name: count, dtype: int64

In [21]:
df_2024 = df[df["last_review"].dt.year == 2024]
df_2024.info()

<class 'pandas.DataFrame'>
Index: 841 entries, 7 to 8217
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              841 non-null    int64
 1   name                            841 non-null    str
 2   host_id                         841 non-null    int64
 3   host_name                       841 non-null    str
 4   neighbourhood                   841 non-null    str
 5   latitude                        841 non-null    float64
 6   longitude                       841 non-null    float64
 7   room_type                       841 non-null    str
 8   price                           648 non-null    float64
 9   minimum_nights                  841 non-null    int64
 10  number_of_reviews               841 non-null    int64
 11  last_review                     841 non-null    datetime64[us]
 12  reviews_per_month               841 non-null    float64
 13  calculated_host_listings_count  841 non-null    int64
 14  availability_365                841 non-null    int64
 15  number_of_reviews_ltm           841 non-null    int64
 16  license                         841 non-null    str
dtypes: datetime64[us](1), float64(4), int64(7), str(5)
memory usage: 118.3 KB

In [22]:
df_2023 = df[df["last_review"].dt.year == 2023]
df_2023.info()

<class 'pandas.DataFrame'>
Index: 278 entries, 71 to 5778
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              278 non-null    int64
 1   name                            278 non-null    str
 2   host_id                         278 non-null    int64
 3   host_name                       278 non-null    str
 4   neighbourhood                   278 non-null    str
 5   latitude                        278 non-null    float64
 6   longitude                       278 non-null    float64
 7   room_type                       278 non-null    str
 8   price                           225 non-null    float64
 9   minimum_nights                  278 non-null    int64
 10  number_of_reviews               278 non-null    int64
 11  last_review                     278 non-null    datetime64[us]
 12  reviews_per_month               278 non-null    float64
 13  calculated_host_listings_count  278 non-null    int64
 14  availability_365                278 non-null    int64
 15  number_of_reviews_ltm           278 non-null    int64
 16  license                         271 non-null    str
dtypes: datetime64[us](1), float64(4), int64(7), str(5)
memory usage: 39.1 KB

In [26]:
df_2025[df_2025["price"].isnull()]["room_type"].value_counts()

room_type
Entire home/apt    419
Private room        57
Shared room          1
Name: count, dtype: int64

In [27]:
df_2025[df_2025["license"].isnull()]["room_type"].value_counts()

room_type
Entire home/apt    46
Private room       10
Name: count, dtype: int64

In [45]:
# cardinalidad para clasificar el tipo de variables
def cardinalidad(df_in, umbral_categoria, umbral_continua):
    
    resultados = []

    for col in df_in.columns:
        # Cardinalidad absoluta
        card = df_in[col].nunique(dropna=True)
        
        # Porcentaje de cardinalidad
        pct = card / len(df_in) * 100
        
        # Clasificación según reglas
        if card == 2:
            tipo = "Binaria"
        
        elif card < umbral_categoria:
            tipo = "Categórica"
        
        else:
            # card >= umbral_categoria → mirar porcentaje
            if pct >= umbral_continua:
                tipo = "Numerica Continua"
            else:
                tipo = "Numerica Discreta"

In [49]:
cardinalidad(df_2025, 12, 0.3)

In [34]:
df_2025["neighbourhood"].dtype
df_2025["room_type"].dtype

In [31]:
df_2025.head(2)

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,96033,"Bonito piso a 200m de la playa, El Palo (Málaga)",510467,Rafael,Este,36.72031,-4.35627,Entire home/apt,58.0,3,274,2025-09-29,1.88,1,324,40,ESFCTU0000290200003588210000000000000000VUT/MA...
1,166473,Perfect Location In Malaga,793360,Fred,Este,36.72031,-4.36108,Private room,28.0,5,102,2025-03-27,0.59,5,288,3,NaN

In [ ]:
|**Columna/Variable** | **Tipo de Variable** |**Descripción** |
|---------------------|-----------------|------------------|
| id | |