In [1]:
import pandas as pd

In [3]:
df_listings = pd.read_csv("./datos/listings.csv")

In [10]:
df_listings.head(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,96033,"Bonito piso a 200m de la playa, El Palo (Málaga)",510467,Rafael,NaN,Este,36.720310,-4.356270,Entire home/apt,58.0,3,274,2025-09-29,1.88,1,324,40,ESFCTU0000290200003588210000000000000000VUT/MA...
1,166473,Perfect Location In Malaga,793360,Fred,NaN,Este,36.720310,-4.361080,Private room,28.0,5,102,2025-03-27,0.59,5,288,3,NaN
2,330760,Malaga Lodge Guesthouse Double room-shared bath.,1687526,Mayte,NaN,Centro,36.729786,-4.413462,Private room,60.0,1,68,2025-09-04,0.41,6,64,12,ESHFTU0000290200004234200060000000000000VFT/MA...
3,340024,NEW APARTMENT IN MALAGA CENTER,1725690,Carlos,NaN,Centro,36.728130,-4.414220,Entire home/apt,61.0,3,322,2025-09-09,2.11,1,297,38,VFT/MA/02334
4,358541,Casa La Maga - Apartment for happy people,1526932,Cristina,NaN,Centro,36.723740,-4.421300,Entire home/apt,87.0,2,405,2025-07-27,2.48,1,195,23,VFT/MA/02288

In [6]:
df = df_listings.copy()

In [ ]:
df.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9714 entries, 0 to 9713
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              9714 non-null   int64
 1   name                            9714 non-null   str
 2   host_id                         9714 non-null   int64
 3   host_name                       9714 non-null   str
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   9714 non-null   str
 6   latitude                        9714 non-null   float64
 7   longitude                       9714 non-null   float64
 8   room_type                       9714 non-null   str
 9   price                           8815 non-null   float64
 10  minimum_nights                  9714 non-null   int64
 11  number_of_reviews               9714 non-null   int64
 12  last_review                     8709 non-null   str
 13  reviews_per_month               8709 non-null   float64
 14  calculated_host_listings_count  9714 non-null   int64
 15  availability_365                9714 non-null   int64
 16  number_of_reviews_ltm           9714 non-null   int64
 17  license                         9587 non-null   str
dtypes: float64(5), int64(7), str(6)
memory usage: 1.3 MB

In [27]:
df.isnull().sum()

id                                   0
name                                 0
host_id                              0
host_name                            0
neighbourhood_group               9714
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price                              899
minimum_nights                       0
number_of_reviews                    0
last_review                       1005
reviews_per_month                 1005
calculated_host_listings_count       0
availability_365                     0
number_of_reviews_ltm                0
license                            127
dtype: int64

In [12]:
df_neighbourhoods = pd.read_csv("./datos/neighbourhoods.csv")

In [16]:
df_neighbourhoods

    neighbourhood_group         neighbourhood
0                   NaN     Bailen-Miraflores
1                   NaN           Campanillas
2                   NaN    Carretera de Cadiz
3                   NaN                Centro
4                   NaN             Churriana
5                   NaN         Ciudad Jardin
6                   NaN   Cruz De Humilladero
7                   NaN                  Este
8                   NaN        Palma-Palmilla
9                   NaN    Puerto de la Torre
10                  NaN  Teatinos-Universidad

In [20]:
df_reviews = pd.read_csv("./datos/reviews.csv")
df_reviews.head()

   listing_id        date
0       96033  2013-10-18
1       96033  2013-11-12
2       96033  2014-04-17
3       96033  2014-05-08
4       96033  2014-05-29

In [19]:
df_reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 487221 entries, 0 to 487220
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   listing_id  487221 non-null  int64
 1   date        487221 non-null  str
dtypes: int64(1), str(1)
memory usage: 7.4 MB

In [23]:
df_reviews["listing_id"].value_counts()

listing_id
30141259               1110
2343063                 900
2336145                 819
35637047                804
13315721                757
                       ...
1508055573682703799       1
1510761711522157265       1
1511086218187507920       1
1512983224037386804       1
1513513040075120429       1
Name: count, Length: 8709, dtype: int64